site_name: "Agentic Platform Engineering"
site_description: Documentation for Agentic Platform Engineering
repo_url: https://github.com/POps-Rox/agentic-platform-engineering
edit_uri: edit/main/docs/

nav:
  - Home: index.md

plugins:
  - techdocs-core

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
